; Flex sensor (TX) -> ESP-NOW -> Motor open-loop (RX)
; Two envs sharing one project. Pick with: pio run -e transmitter / -e receiver

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:transmitter]
build_src_filter = +<transmitter.cpp>

[env:receiver]
build_src_filter = +<receiver.cpp>
lib_deps =
    askuric/Simple FOC@^2.3.4
build_flags =
    -DCORE_DEBUG_LEVEL=3
